apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfonarmesteleder
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfonarmesteleder.nais.preprod.local"
    - "https://syfonarmesteleder.dev-fss-pub.nais.io"
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /azuread/data/dev/creds/syfonarmesteleder
        mountPath: /secrets/azuread/syfonarmesteleder
      - kvPath: serviceuser/data/dev/srvsyfonarmesteleder
        mountPath: /secrets/serviceuser
  webproxy: true
  env:
    - name: SERVICESTRANGLER_ID
      value: abb15e65-89f6-475e-95e3-be6a31cc64c0
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/.well-known/openid-configuration
    - name: SYFOMOTEADMIN_ID
      value: 4a100698-9ddc-4441-b42c-ec2ad8825b88
    - name: JWT_ISSUER
      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: SYFONARMESTELEDER_DB_URL
      value: jdbc:postgresql://b27dbvl008.preprod.local:5432/syfonarmesteleder
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
