apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfonarmesteleder
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  accessPolicy:
    inbound:
      external:
        - host: tt02.altinn.no
        - host: api-gw-q1.oera.no
  gcp:
    sqlInstances:
      - name: syfonarmesteleder-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: syfonarmesteleder
            envVarPrefix: NAIS_DATABASE
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfonarmesteleder.dev.nav.no"
  kafka:
    pool: nav-dev
  vault:
    enabled: false
  filesFrom:
    - secret: syfonarmesteleder-secrets
  envFrom:
    - secret: syfonarmesteleder-api-keys
  webproxy: true
  env:
    - name: SERVICESTRANGLER_ID
      value: abb15e65-89f6-475e-95e3-be6a31cc64c0
    - name: ARBEIDSGIVERTILGANG_ID
      value: 3f567c84-4912-4acf-88ef-9f0dcfc2ae2b
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/.well-known/openid-configuration
    - name: SYFOSOKNAD_ID
      value: 281ba984-745f-48b8-a79c-9444b8688361
    - name: SYFOVARSEL_ID
      value: 3f091637-cadb-4d0e-8deb-05a27e776049
    - name: SYFOBRUKERTILGANG_ID
      value: e92cacff-fa81-4174-a9d9-e139e38683b9
    - name: SYFOMOTEADMIN_ID
      value: 4a100698-9ddc-4441-b42c-ec2ad8825b88
    - name: SYFOOPPFOLGINGSPLANSERVICE_ID
      value: 41561812-fdcc-4933-a147-f481a8b9fb18
    - name: MODIASYFOREST_ID
      value: 54b2b721-2825-4895-aceb-40cf6103681e
    - name: SYFOSMALTINN_ID
      value: 74bce231-869c-4a59-9830-ac479b591bf0
    - name: JWT_ISSUER
      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SYKMELDINGERBACKEND_ID
      value: cfbe515d-ea06-424d-a29e-43e0f5dfa903
    - name: KAFKA_CLIENT_ID
      value: syfonarmesteleder
