apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfonarmesteleder
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  accessPolicy:
    inbound:
      external:
        - host: tt02.altinn.no
        - host: api-gw-q1.oera.no
  gcp:
    sqlInstances:
      - name: syfonarmesteleder-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: syfonarmesteleder
            envVarPrefix: NAIS_DATABASE
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 2560m
      memory: 2Gi
    requests:
      cpu: 2048m
      memory: 2Gi
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfonarmesteleder.intern.nav.no"
  kafka:
    pool: nav-prod
  vault:
    enabled: false
  filesFrom:
    - secret: syfonarmesteleder-secrets
  envFrom:
    - secret: syfonarmesteleder-api-keys
  webproxy: true
  env:
    - name: SERVICESTRANGLER_ID
      value: 642cea5c-35d1-4744-806f-03104dbdf4cc
    - name: ARBEIDSGIVERTILGANG_ID
      value: 24059ae3-654d-4aaf-9c04-a1cb7b510bb4
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    - name: SYFOSOKNAD_ID
      value: ffca591d-dfc9-4ecf-9ac2-050d75b39fc0
    - name: SYFOVARSEL_ID
      value: cec525e5-44e7-459f-80c9-e8c90424d951
    - name: SYFOBRUKERTILGANG_ID
      value: 4fe1b104-7c07-4fc1-9d5d-be7ea5232690
    - name: SYFOMOTEADMIN_ID
      value: 54649979-fe0a-4f6c-adfe-8616e4602954
    - name: SYFOOPPFOLGINGSPLANSERVICE_ID
      value: 970b2069-0b53-492f-bd7a-acadfa211e9f
    - name: MODIASYFOREST_ID
      value: a14ca2f1-fd72-4f2a-9837-f0aa6a718ffd
    - name: SYFOSMALTINN_ID
      value: ffdc358b-b97c-470e-a0c8-bf147b5e8561
    - name: JWT_ISSUER
      value: https://sts.windows.net/62366534-1ec3-4962-8869-9b5535279d0b/
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: SYKMELDINGERBACKEND_ID
      value: e084350d-f7af-4b29-b573-e01f1a82fc19
    - name: KAFKA_CLIENT_ID
      value: syfonarmesteleder
