apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfonarmesteleder
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 2560m
      memory: 2Gi
    requests:
      cpu: 2048m
      memory: 2Gi
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfonarmesteleder.nais.adeo.no"
    - "https://syfonarmesteleder.prod-fss-pub.nais.io"
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /azuread/data/prod/creds/syfonarmesteleder
        mountPath: /secrets/azuread/syfonarmesteleder
      - kvPath: serviceuser/data/prod/srvsyfonarmesteleder
        mountPath: /secrets/serviceuser
  webproxy: true
  env:
    - name: SERVICESTRANGLER_ID
      value: 642cea5c-35d1-4744-806f-03104dbdf4cc
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    - name: SYFOBRUKERTILGANG_ID
      value: 4fe1b104-7c07-4fc1-9d5d-be7ea5232690
    - name: SYFOMOTEADMIN_ID
      value: 54649979-fe0a-4f6c-adfe-8616e4602954
    - name: SYFOOPPFOLGINGSPLANSERVICE_ID
      value: 970b2069-0b53-492f-bd7a-acadfa211e9f
    - name: JWT_ISSUER
      value: https://sts.windows.net/62366534-1ec3-4962-8869-9b5535279d0b/
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: SYFONARMESTELEDER_DB_URL
      value: jdbc:postgresql://A01DBVL010.adeo.no:5432/syfonarmesteleder
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
